name: dtml-simple-gitops
description: pushes changes to gitops repository
author: datamole-ai
branding:
  icon: 'git-pull-request'
  color: 'green'

inputs:
  key:
    description: 'update value of this key'
    required: true
  value:
    description: 'value to update'
    required: true
    default: ${{ github.sha }}
  valuesFile:
    description: 'path to values file'
    required: true
  commitMessage:
    description: 'Commit message'
    required: true
    default: ${{ github.event.head_commit.message }}
runs:
  using: "composite"
  steps:
  - shell: bash
    env:
      FULL_PATH: ${{ inputs.key }}
      NEW_VALUE: ${{ inputs.value }}
      VALUES_FILE: ${{ inputs.valuesFile }}
      COMMIT_MESSAGE: ${{ inputs.commitMessage }}
    
    run: bash ${{ github.action_path }}/action.sh
